# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d173ab74ce24914e90e0dabf3938ed65b20e520df5cbec1f69adb62f08748381a2c94e8f1aa48d49ce4665ee3648463a9b46d5bfd632314862432c52fec3d337

test:
  secret_key_base: 4464a1ee81f76601d2b1d4932e3d4029c12900708e0b1036222cc5191aecac648b2cda6442754797a22657ad67e88665c52db396ab2e9e08d7c161875eabe145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
